# Generated by Django 5.2.8 on 2026-04-05 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_signup_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(choices=[('community_hall', 'Community Hall'), ('terrace', 'Terrace'), ('bbq_area', 'BBQ Area'), ('swimming_pool', 'Swimming Pool'), ('conference_room', 'Conference Room')], max_length=30)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('morning', 'Morning (6 AM – 12 PM)'), ('afternoon', 'Afternoon (12 PM – 6 PM)'), ('evening', 'Evening (6 PM – 11 PM)')], max_length=20)),
                ('purpose', models.CharField(max_length=200)),
                ('num_guests', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bot.signup')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electricity', 'Electricity'), ('noise', 'Noise'), ('cleanliness', 'Cleanliness'), ('lift', 'Lift'), ('parking', 'Parking'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('date_resolved', models.DateTimeField(blank=True, null=True)),
                ('secretary_remarks', models.TextField(blank=True, default='')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='bot.signup')),
            ],
            options={
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('maintenance', 'Maintenance'), ('meeting', 'Meeting'), ('emergency', 'Emergency'), ('event', 'Event'), ('water_supply', 'Water Supply'), ('electricity', 'Electricity')], default='general', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='bot.signup')),
            ],
            options={
                'ordering': ['-is_urgent', '-posted_on'],
            },
        ),
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=150)),
                ('visitor_contact', models.CharField(max_length=15)),
                ('purpose', models.CharField(max_length=200)),
                ('expected_date', models.DateField()),
                ('expected_time', models.TimeField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='approved', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=20)),
                ('flat_number', models.CharField(blank=True, default='', max_length=20)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('flat_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='bot.signup')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_visitors', to='bot.signup')),
            ],
            options={
                'ordering': ['-expected_date', '-expected_time'],
            },
        ),
    ]
